// Generated by scripts/sync_models.py — DO NOT EDIT MANUALLY.
// Re-run `make sync-models` after changing any file in backend/app/schemas/.
//
// JSONDecoder setup required in your app (BackendAPIService or a shared decoder):
//   decoder.dateDecodingStrategy = .iso8601
//   (CodingKeys handle snake_case → camelCase; no keyDecodingStrategy override needed)

import Foundation

/// Auto-generated from `ProfileOut` (backend/app/schemas).
struct ProfileOut: Decodable, Equatable {
    let id: UUID
    let displayName: String?
    let avatarUrl: String?
    let createdAt: Date

    enum CodingKeys: String, CodingKey {
        case id
        case displayName = "display_name"
        case avatarUrl = "avatar_url"
        case createdAt = "created_at"
    }
}
